<?xml version="1.0" encoding="utf-8"?><Database Name="MandhegParkingSystem" Class="MandhegParkingSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MandhegParkingSystem;Integrated Security=True" SettingsObjectName="PC_KAB_KLATEN_JOKO_SUPRIYANTO.Properties.Settings" SettingsPropertyName="MandhegParkingSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Employee_ParkingData" Member="ParkingDatas" ThisKey="id" OtherKey="employee_id" Type="ParkingData" />
    </Type>
  </Table>
  <Table Name="dbo.VehicleType" Member="VehicleTypes">
    <Type Name="VehicleType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="VehicleType_HourlyRate" Member="HourlyRates" ThisKey="id" OtherKey="vehicle_type_id" Type="HourlyRate" />
      <Association Name="VehicleType_Vehicle" Member="Vehicles" ThisKey="id" OtherKey="vehicle_type_id" Type="Vehicle" />
    </Type>
  </Table>
  <Table Name="dbo.HourlyRates" Member="HourlyRates">
    <Type Name="HourlyRate">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="membership_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vehicle_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HourlyRate_ParkingData" Member="ParkingDatas" ThisKey="id" OtherKey="hourly_rates_id" Type="ParkingData" />
      <Association Name="VehicleType_HourlyRate" Member="VehicleType" ThisKey="vehicle_type_id" OtherKey="id" Type="VehicleType" IsForeignKey="true" />
      <Association Name="Membership_HourlyRate" Member="Membership" ThisKey="membership_id" OtherKey="id" Type="Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="membership_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Member_Vehicle" Member="Vehicles" ThisKey="id" OtherKey="member_id" Type="Vehicle" />
      <Association Name="Membership_Member" Member="Membership" ThisKey="membership_id" OtherKey="id" Type="Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Membership" Member="Memberships">
    <Type Name="Membership">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Membership_HourlyRate" Member="HourlyRates" ThisKey="id" OtherKey="membership_id" Type="HourlyRate" />
      <Association Name="Membership_Member" Member="Members" ThisKey="id" OtherKey="membership_id" Type="Member" />
    </Type>
  </Table>
  <Table Name="dbo.ParkingData" Member="ParkingDatas">
    <Type Name="ParkingData">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="license_plate" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="vehicle_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="employee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hourly_rates_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datetime_in" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="datetime_out" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="amount_to_pay" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Employee_ParkingData" Member="Employee" ThisKey="employee_id" OtherKey="id" Type="Employee" IsForeignKey="true" />
      <Association Name="HourlyRate_ParkingData" Member="HourlyRate" ThisKey="hourly_rates_id" OtherKey="id" Type="HourlyRate" IsForeignKey="true" />
      <Association Name="Vehicle_ParkingData" Member="Vehicle" ThisKey="vehicle_id" OtherKey="id" Type="Vehicle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vehicle" Member="Vehicles">
    <Type Name="Vehicle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vehicle_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="member_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="license_plate" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Vehicle_ParkingData" Member="ParkingDatas" ThisKey="id" OtherKey="vehicle_id" Type="ParkingData" />
      <Association Name="Member_Vehicle" Member="Member" ThisKey="member_id" OtherKey="id" Type="Member" IsForeignKey="true" />
      <Association Name="VehicleType_Vehicle" Member="VehicleType" ThisKey="vehicle_type_id" OtherKey="id" Type="VehicleType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>